# config.yaml
department_list:
  - 'All'
  - 'Modeling'
  - 'Concept'
  - 'Surfacing'
  - 'Rigging'
  - 'Layout'
  - 'Animation'
  - 'FX'
  - 'CharFX'
  - 'Lighting'
  - 'Compositing'
  - 'Mattepainting'
  - 'Rotoscoping'
  - 'Tracking'

task_list:
  - 'All'
  - 'Modeling'
  - 'Concept'
  - 'Surfacing'
  - 'Rigging'
  - 'Layout'
  - 'Animation'
  - 'FX'
  - 'CharFX'
  - 'Lighting'
  - 'Compositing'
  - 'Mattepainting'
  - 'Rotoscoping'
  - 'Tracking'
